import Link from "next/link";
import type { ReactNode } from "react";

import { AppConfig } from "@/utils/AppConfig";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import Head from "next/head";
type IHomeProps = {
  meta?: ReactNode;
  children: ReactNode;
};

const HomeLayout = (props: IHomeProps) => (
  <div className="home-layout-wrapper">
    {props.meta}
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css"
      />
    </Head>
    <div className="home-wrapper">
      <Header />
      <main>{props.children}</main>
      <Footer />
    </div>
  </div>
);

export { HomeLayout };
